### ISSUE TITLE
What is an "IP forwarding path"?

### ISSUE THREAD

**Issue by DavidSchinazi** [tfpauly/draft-age-masque-connect-ip#1]
The draft currently mentions an "IP forwarding path" (or elsewhere a "path for proxying IP packets") without defining what that term means. It's ambiguous because "path" is a [well-defined term in HTTP](https://datatracker.ietf.org/doc/html/rfc3986#section-3.3). I'd propose we replace this use of the word "path" with the word "tunnel" which is [well-defined for CONNECT](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-semantics-18#section-9.3.6).

**Comment by tfpauly** [comment]
Yes, "IP forwarding tunnel" sounds fine to me.

**Comment by mirjak** [comment]
Yes tunnel is good. Or maybe association in the context of handling state st the proxy.
