### ISSUE TITLE
Is ROUTE_ADVERTISEMENT part of the base spec?

### ISSUE THREAD

**Issue by mirjak** [tfpauly/draft-age-masque-connect-ip#13]
I would like to discuss this question a bit more before we submit the -00 version. Route advertising (and requesting) makes sense as a general concept to limit the destination address space, similarly as address requesting defines the source address space. However it is less clear to me if we need to support dynamic handling of routes in the base spec. I would assume that in many deployments the proxy has a fixed set of routes that are supported and that can be preconfigured and might be provided to the client together with the proxy address/proxy discovery. What exactly is the use case for handling this dynamically? And is that use case in scope for the base spec?

**Comment by achernya** [comment]
I'm not sure what you mean by "dynamic handling of routes in the base spec" -- how else would you do it? The only way I can think of is a-priori out of band knowledge of what' reachable through the proxy, which would make the base spec not useful by itself.

**Comment by tfpauly** [comment]
@mirjak I think that some form of assigning the route is absolutely required if we want "flow mode", since it is what tells the client they have a specific route as opposed to a full tunnel.

**Comment by gloinul** [comment]
I think providing the reachability information is relevant part of the base spec. However, I am not convinced that the current proposal solves the flow mode, as it is not a sufficient selector for what is an IP flow in the sense of the IP flow label.

**Comment by achernya** [comment]
Let's continue the IP flow label discussion on #9.

**Comment by tfpauly** [comment]
Tracking this with #25
