### ISSUE TITLE
ROUTE_ADVERTISEMENT Capsule needs clarification of fields

### ISSUE THREAD

**Issue by gloinul** [tfpauly/draft-age-masque-connect-ip#16]
I think the field description needs updates. The IP adress is after all an prefix that is masked by the specified number of bits. That is not quite clear yet. 

However, I think the question if this range should support excluding one or more sub-ranges needs to be sorted out also.

**Comment by DavidSchinazi** [comment]
> I think the field description needs updates. The IP adress is after all an prefix that is masked by the specified number of bits. That is not quite clear yet.

The specification of the `IP Prefix Length` field currently states `Length of the IP Prefix of the advertised route, in bits. MUST be lesser or equal to the length of the IP Address field, in bits.`. Is that unclear? If so, can you help provide text to help make it clearer?

> However, I think the question if this range should support excluding one or more sub-ranges needs to be sorted out also.

Agreed, that's discussed in #3
