### ISSUE TITLE
Path or query?

### ISSUE THREAD

**Issue by DavidSchinazi** [tfpauly/draft-age-masque-connect-ip#2]
Section 3.1 (Limiting Request Scope) uses the term [path](https://datatracker.ietf.org/doc/html/rfc3986#section-3.3) but then it talks about variables which are part of the [query](https://datatracker.ietf.org/doc/html/rfc3986#section-3.4), not the path. Do we mean query here, or am I misunderstanding? As a reminder, the ":path" pseudo-header [in h2](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.3) and h3 contains both the path and the query separated by a question mark.

**Comment by tfpauly** [comment]
Yes, this should be the query part of the :path pseudo-header

**Comment by achernya** [comment]
Can I propose we close this issue out entirely in favor of switching to headers as per #7? Then we avoid the confusion around what "path" is here. I've left some thoughts on the philosophy of path in my comment there.
