### ISSUE TITLE
Missing ROUTE_REJECTION capsule

### ISSUE THREAD

**Issue by DavidSchinazi** [tfpauly/draft-age-masque-connect-ip#3]
The current version of the draft contains the ROUTE_ADVERTISEMENT capsule but is missing the ROUTE_REJECTION capsule. It's very common for networks to want to advertise routes such as "I can handle all of IPv4 space minus RFC 1918 space" and that becomes incredibly painful if you don't have a way to subtract prefixes. An alternate solution is to use an address start/address end encoding like [IKEv2 traffic selectors](https://datatracker.ietf.org/doc/html/rfc7296#section-3.13.1), but if we want to use a prefix-based encoding we need a way to cut out holes from prefixes.

**Comment by tfpauly** [comment]
Oh, is that what the rejection capsule was for? I guess I'd just rather have the route advertisement itself provide a list of exceptions, rather than tying it to a separate capsule?

**Comment by DavidSchinazi** [comment]
Yes, that would also work. This is just a matter of encoding.

**Comment by achernya** [comment]
The nice thing about the rejection capsule is it allows you to remove announcements that were previous present without having to re-send a full routing table. I would prefer keeping it, as it allows for more efficient transmission of information. (I disagree it's just a matter of encoding.)

**Comment by mirjak** [comment]
Actually sending a full routing table seems like the safer way to go. And given you don’t do that very often, I don’t think we need to worry about overhead.

**Comment by gloinul** [comment]
I will disagree with my co-author. I think the basic case for what in most cases are the equivalent to the default route for a host on a LAN segment would be good to have in a reasonable compact form. I think the question to ask here is if we in general need a mechanism to specify an IP prefix with one or more carved out sub-prefixes. I that requirement may apply to both advertising and rejecting/removing a prefix. In the removing maybe it is possible to specify the whole prefix without carve out sub-prefixes.

**Comment by tfpauly** [comment]
Maybe call with ROUTE_WITHDRAW instead of reject
