### ISSUE TITLE
SETTINGS in example are confusing

### ISSUE THREAD

**Issue by DavidSchinazi** [tfpauly/draft-age-masque-connect-ip#4]
I'm confused by the use of `SETTINGS_ENABLE_CONNECT_[..]` in the example. It makes me wonder if this document is defining a new setting that I don't know about. Can we instead just spell out `SETTINGS_ENABLE_CONNECT_PROTOCOL`?

**Comment by DavidSchinazi** [comment]
I just noticed that this comes from RFC 8441, still would rather we spell out the name of the setting :)

**Comment by tfpauly** [comment]
Yes, I took it from RFC 8441. I don't particularly care about the style here.
