### ISSUE TITLE
What does the URI path represent?

### ISSUE THREAD

**Issue by DavidSchinazi** [tfpauly/draft-age-masque-connect-ip#5]
(This is related to #2, and here I'm assuming that Section 3.1 meant query and not path.)

What does the URI path represent? The examples use a path of `/vpn` and `/proxy`. Is the intention to let deployments decide what a path means? That makes sense to me but we should mention it.

**Comment by DavidSchinazi** [comment]
Perhaps all we need is a reference to [how those are defined for the http and https schemes](https://www.rfc-editor.org/rfc/rfc7230.html#section-2.7.1):

> The hierarchical path component and optional query component serve as an identifier for a potential target resource within that origin server's name space.

**Comment by tfpauly** [comment]
The `/vpn` and `/proxy` examples were just arbitrary names that were examples of paths the proxies could run on. Adding a reference and explaining these are examples sounds good.

**Comment by gloinul** [comment]
To my understanding we currently don't specify multiple different functionalities based on the URI path component. Therefore we can work without any type of well-known URI suffix https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml#well-known-uris-1 and the discovery procedure here is that the MASQUE client need to be configured/supplied with a base URI that gives the proxy as host component, and the path that is relevant on that proxy to invoke the MASQUE service. So unless we want to something more advance I think we can just make clear that the masque service resource is identified however the proxy want it to be.

**Comment by achernya** [comment]
I think that having MASQUE be able to work with any URI is a feature, and whether someone else down the line wants to make an auto-discovery for MASQUE-based proxies, either with .well-known or some other mechanism, should be a separate discussion (and likely separate document).
