### ISSUE TITLE
Are arbitrary query parameters allowed?

### ISSUE THREAD

**Issue by DavidSchinazi** [tfpauly/draft-age-masque-connect-ip#7]
Is it legal to send a CONNECT-IP request where `:path = /proxy?target=target.example.com&ipproto=1&foo=bar` ?

The more I think about this, the more I think that the target and ipproto would be better conveyed by two new HTTP headers instead of query parameters. Is there value in having these present in the URI?

**Comment by DavidSchinazi** [comment]
From reading [the definition of the query](https://www.rfc-editor.org/rfc/rfc7230.html#section-2.7.1) I'm even more inclined to use a header instead.

**Comment by tfpauly** [comment]
Yup, I'm fine spelling this as headers too! (That's more like the original Ericsson doc)

The reason I tried with the parameters is that it was a suggestion we had from Erik Nygren, etc, from one of the initial requests to use Extended Connect. This seems like something to ask the working group.

**Comment by tfpauly** [comment]
I think this would fall into the category of URI-template, like what's done for DoH GET requests. So it should be allowed.

**Comment by DavidSchinazi** [comment]
Using a URI template would be easier to reason about than the current text, so I'd be in favor of that if we decided to go with path/query instead of a new header.

**Comment by tfpauly** [comment]
Yeah, I should have spelled it out as a template

**Comment by achernya** [comment]
Thinking about this some more, I feel like we should avoid specifying meaning to components of path, including the query-params. I think we should move target and ipproto to headers (as David suggested), and allow path to be application defined. I was thinking of path to be more like /my-cool/proxy/with-auth, like an HTML, content to set "personality", not a way to specify core operating parameters like these.

**Comment by DavidSchinazi** [comment]
I think the question we should answer is: Do we want the target/ip_proto in the URI?

The way I'm visualizing this is that you could configure your client to use a given proxy by typing in a URI into the client software (e.g. `https://vpnprovider.example.com/david?egress=ohio`) - whereas the target/ip_proto are dynamic components that are picked by my proxy software in response to what networking the OS needs to do.

All this to say that the more I think about it the more I think headers are preferable

**Comment by mirjak** [comment]
I agree to David’s last comment that target and ip_proto are rather parameters that are set by the proxy software and therefore I also tend to prefer headers. It also seems we would potential otherwise overload the URI scheme too much that still could be useful for other information (as in David’s example above)

**Comment by gloinul** [comment]
I frankly don't understand the implications of either of choices to give an opinion here. I don't know if hedaers will be easier or harder to get through intermediaries? 

I think maybe the best way forward on this issue is to actually write it up and post to the mailing list.

**Comment by achernya** [comment]
Both headers and query params are equally easy to get through intermediaries in my experience. I would prefer we try to hash this out among ourselves before going to the mailing list.
