### ISSUE TITLE
Why do ADDRESS_ASSIGN and ADDRESS_REQUEST contain an IP Protocol field?

### ISSUE THREAD

**Issue by DavidSchinazi** [tfpauly/draft-age-masque-connect-ip#8]
I understand the value of the IP Protocol field on the ROUTE_ADVERTISEMENT capsule, but not on ADDRESS_ASSIGN or ADDRESS_REQUEST. What purpose does it serve?

**Comment by tfpauly** [comment]
I think this is an important point—we're asking for a scoped traffic selector that only needs to be able to route a specific protocol (like ICMP, UDP, TCP). This allows the endpoint to know if it can have the tunnel share an address with other requests that use a different protocol.

**Comment by DavidSchinazi** [comment]
The ADDRESS_ASSIGN and ADDRESS_REQUEST capsules are not about traffic selectors, they're about configuration. Using terminology from RFC 7296:

* ROUTE_ADVERTISEMENT maps to an IKEv2 Traffic Selector (i.e. I'll accept to forward your packets if they're destined to this IP prefix and IP proto)
* ADDRESS_ASSIGN maps to an IKEv2 Configuration Payload with Configuration Attribute Type set to INTERNAL_IP6_ADDRESS (i.e. here is an address you can use to refer to yourself)

I think it might make sense to add a new ROUTE_REQUEST capsule that would emulate what you're describing (i.e. please tell me if you're willing to forward packets to this IP prefix and protocol), but we shouldn't overload ADDRESS_REQUEST for this purpose. If you look at the Proxied ICMP Flow Example that's currently in the spec, everything still works if you remove the IP Protocol field from ADDRESS_ASSIGN.

Another potential feature we could possibly add is "this IP address I'm assigning to you is tied to this traffic selector that I just advertised" but I'm not sure we need that.

**Comment by DavidSchinazi** [comment]
Address assignment and what addresses I can send from are separate concepts: assignment implies that I'll reply to packets sent to this address.

But back to my original question, IP packets contain one IP Protocol field not two (there are no separate source and destination IP Protocol fields), so I don't see the need for that on the "send from" side, we only need it on the "send to" side. What breaks if we remove the IP Protocol field from ADDRESS_ASSIGN and ADDRESS_REQUEST?

**Comment by tfpauly** [comment]
The reason I feel it is important is that the address assignment may be specific to that protocol, if the address is used for other things on other protocols. For example, I could have an address I use for many other clients for outbound CONNECT requests, which I also allow one client to use for an ICMP message to a particular destination. 

Now, technically, you could make sure to only provide the ICMP client with routes to destinations that are also marked for ICMP, but it feels like the protocol is keeping open the possibility to request on this same HTTP request a route that has an entirely different protocol, using the same address. So, I’d like to know on the client if the proxy has granted me a general purpose IP address, or a limited use one.

**Comment by DavidSchinazi** [comment]
Tying addresses to ip protocols feels like a half-solution. Architecturally, it would make more sense to tie the address to a full traffic selector (as in the ip protocol, but also the routes). I think it'll be more common for folks to want to convey "use this IP to access this subnet" than "use this IP for this protocol" so if we support one we should support both.

But for simplicity of the base spec, I'd rather we not have this for now because it makes it harder to reason about what address assignment means.

**Comment by achernya** [comment]
Taking a step back, I think having the ip protocol number in ROUTE_ADVERTISEMENT is already weird (at least, with that name). However, if we accept that IP protocol number needs to be present in the route advertisement, then I somewhat see the reasoning for having the address assignment/request have the parallel.

That said, I'm having a hard time seeing the use case for wanting to offer a route advertisement that is specific to a specific IP protocol --- why does that information need to be there? Presumably once you have a route, you can use it for all IP protocol numbers, and the thing that you need is an assigned address for use with a specific protocol? How would you use the routing information when an ipproto is attached? Are they separate tables, or do you first do a LPM on the IP range and then look at the permitted ipprotos for the destination?

**Comment by mirjak** [comment]
I also see an security aspect here, where you want to configure you proxy to only allow forwarding of certain protocols (and the proxy will check the ip protocol field before forwarding)

**Comment by gloinul** [comment]
I guess this comes into the area where we had specified a incoming traffic selector into the IP payload where a pattern, a byte offset and length where specified so that one could pick up for example UDP destination port.

**Comment by achernya** [comment]
I'm not fond of the byte-offset design as it is brittle in the face of IPv6 with header extensions. That gets into the type of complexity that I feel we should be aiming to avoid in the base draft, and why we agreed that port multiplexing (or other protocol-specific concerns) were definitely out of scope.
